discord:
  # Put your discord ID here so the webhook may tag you for notifs.
  # optional
  id: "your discord ID # here"
  # optional
  webhooks:
    roi report: "webhook url here"

# optional
custom rpcs: ["customrpc1_here"]